сохранение файлов
alexonlyman/WebRecipe pull request #2
Opened 2023-02-01 10:15 UTC by alexonlyman

2023-02-01 18:25 UTC, OlgaLugacheva requested changes

2023-02-01 18:25 UTC, OlgaLugacheva commented on src/main/java/skypro/webrecipe/services/Impl/RecipeServiseImpl.java
> +            e.getStackTrace();
лучше бросать свое исключение в таких случаях а не выводит стек трейс

2023-02-06 16:04 UTC, isavinov requested changes

2023-02-06 16:04 UTC, isavinov commented on src/main/java/skypro/webrecipe/services/FileSirvice.java
> +public interface FileSirvice {
Опечатка - FileS**e**rvice

2023-02-06 16:04 UTC, isavinov commented on src/main/java/skypro/webrecipe/controllers/FilesController.java
> +            e.printStackTrace();
В методе /download выкидывается RuntimeException, в методе /import ошибка логгируется. Лучше привести к единому варианту и выкидывать и там и там RuntimeException

2023-02-06 16:04 UTC, isavinov commented on src/main/java/skypro/webrecipe/controllers/IngredientController.java
> +        return ResponseEntity.ok().body(ingredietn);
опечатка - ingredient

2023-02-06 16:04 UTC, isavinov commented on src/main/java/skypro/webrecipe/services/Impl/FileServiceImpl.java
> +            e.getStackTrace();
в методах saveToFile и cleanDataFile - IOException просто логгируется, в методе readFromFile - пробрасывает наружу RuntimeException. Это сделано специально?

2023-02-06 16:04 UTC, isavinov commented on src/main/java/skypro/webrecipe/services/Impl/IngredientServiceImpl.java
> +        } catch (RuntimeException e) {
Видимо лишний try - RuntimeException не требует обязательной обработки, и здесь он просто пробрасывается выше.

2023-02-07 05:12 UTC, alexonlyman commented on src/main/java/skypro/webrecipe/services/Impl/FileServiceImpl.java
> +            e.getStackTrace();
Да, но у меня в любом случае этот метод не хочет работать, вне зависимости логгирую ли я ошибку либо выбрасываю RuntimeException

2023-02-07 05:16 UTC, alexonlyman commented on src/main/java/skypro/webrecipe/services/Impl/FileServiceImpl.java
> +            Files.writeString(Path.of(dataFilePath, dataFileName), json);
еще хотел спросить, почему нельзя использовать тут Files.createFile?

2023-02-07 08:42 UTC, isavinov commented on src/main/java/skypro/webrecipe/services/Impl/FileServiceImpl.java
> +            Files.writeString(Path.of(dataFilePath, dataFileName), json);
Я так понимаю на этом этапе файл у тебя уже создан, тебе в него только данные записать надо

2023-02-08 19:44 UTC, merged